import { Jugador } from "../../models/Jugador.js";

// Planteles emblemáticos de 8 equipos de futbol argentinos
export const jugadoresFutbol: Record<string, Jugador[]> = {
  "Boca Juniors": [
    new Jugador("Roberto Abbondanzieri", 32, "Arquero"),
    new Jugador("Hugo Ibarra", 31, "Defensor"),
    new Jugador("Rolando Schiavi", 30, "Defensor"),
    new Jugador("Nicolás Burdisso", 24, "Defensor"),
    new Jugador("Clemente Rodríguez", 25, "Defensor"),
    new Jugador("Sebastián Battaglia", 27, "Mediocampista"),
    new Jugador("Diego Cagna", 32, "Mediocampista"),
    new Jugador("Juan Román Riquelme", 28, "Mediocampista"),
    new Jugador("Marcelo Delgado", 29, "Delantero"),
    new Jugador("Martín Palermo", 31, "Delantero"),
    new Jugador("Guillermo Barros Schelotto", 32, "Delantero"),
    // En caso de probar validacion por cupo de equipo
    // Descomentar la linea de abajo, y volver a ejecutar el flujo
    // new Jugador("Carlos Tevez", 20, "Delantero"),
  ],
  "River Plate": [
    new Jugador("Germán Lux", 23, "Arquero"),
    new Jugador("Eduardo Tuzzio", 29, "Defensor"),
    new Jugador("Celso Ayala", 32, "Defensor"),
    new Jugador("Ricardo Rojas", 28, "Defensor"),
    new Jugador("Ariel Garcé", 25, "Defensor"),
    new Jugador("Leonardo Astrada", 33, "Mediocampista"),
    new Jugador("Javier Mascherano", 20, "Mediocampista"),
    new Jugador("Lucho González", 23, "Mediocampista"),
    new Jugador("Marcelo Gallardo", 28, "Mediocampista"),
    new Jugador("Fernando Cavenaghi", 21, "Delantero"),
    new Jugador("Javier Saviola", 22, "Delantero"),
  ],
  Independiente: [
    new Jugador("Luis Islas", 34, "Arquero"),
    new Jugador("Jorge Bermúdez", 32, "Defensor"),
    new Jugador("Carlos Matheu", 25, "Defensor"),
    new Jugador("Gabriel Milito", 27, "Defensor"),
    new Jugador("Lucas Pusineri", 28, "Mediocampista"),
    new Jugador("Federico Insúa", 25, "Mediocampista"),
    new Jugador("Daniel Montenegro", 27, "Mediocampista"),
    new Jugador("Andrés Silvera", 29, "Delantero"),
    new Jugador("Nicolás Frutos", 26, "Delantero"),
    new Jugador("Sergio Agüero", 17, "Delantero"),
    new Jugador("Gustavo López", 30, "Mediocampista"),
  ],
  "Racing Club": [
    new Jugador("Gustavo Campagnuolo", 30, "Arquero"),
    new Jugador("Francisco Maciel", 28, "Defensor"),
    new Jugador("Gabriel Loeschbor", 27, "Defensor"),
    new Jugador("Matías Lequi", 22, "Defensor"),
    new Jugador("Carlos Arano", 24, "Defensor"),
    new Jugador("Adrián Bastía", 25, "Mediocampista"),
    new Jugador("Esteban Cambiasso", 21, "Mediocampista"),
    new Jugador("Maximiliano Estévez", 23, "Delantero"),
    new Jugador("Diego Milito", 22, "Delantero"),
    new Jugador("Lisandro López", 21, "Delantero"),
    new Jugador("Chatruc", 26, "Mediocampista"),
  ],
  "San Lorenzo": [
    new Jugador("Sebastián Saja", 25, "Arquero"),
    new Jugador("Leandro Álvarez", 27, "Defensor"),
    new Jugador("Walter Samuel", 28, "Defensor"),
    new Jugador("Sebastián Méndez", 29, "Defensor"),
    new Jugador("Diego Placente", 25, "Defensor"),
    new Jugador("Leandro Romagnoli", 23, "Mediocampista"),
    new Jugador("Ernesto Chevantón", 24, "Mediocampista"),
    new Jugador("Pablo Michelini", 28, "Mediocampista"),
    new Jugador("Rodrigo Astudillo", 26, "Delantero"),
    new Jugador("Bernardo Romeo", 23, "Delantero"),
    new Jugador("Alberto Acosta", 34, "Delantero"),
  ],
  "Vélez Sarsfield": [
    new Jugador("José Luis Chilavert", 34, "Arquero"),
    new Jugador("Roberto Trotta", 32, "Defensor"),
    new Jugador("Mauricio Pellegrino", 29, "Defensor"),
    new Jugador("Fabián Cubero", 25, "Defensor"),
    new Jugador("Raúl Cardozo", 33, "Defensor"),
    new Jugador("Christian Bassedas", 27, "Mediocampista"),
    new Jugador("Marcelo Gómez", 28, "Mediocampista"),
    new Jugador("Víctor Zapata", 24, "Mediocampista"),
    new Jugador("Martín Posse", 26, "Delantero"),
    new Jugador("Patricio Camps", 27, "Delantero"),
    new Jugador("Carlos Compagnucci", 30, "Mediocampista"),
  ],
  "Estudiantes LP": [
    new Jugador("Andújar", 26, "Arquero"),
    new Jugador("Angeleri", 25, "Defensor"),
    new Jugador("Desábato", 30, "Defensor"),
    new Jugador("Alayes", 29, "Defensor"),
    new Jugador("Re", 28, "Defensor"),
    new Jugador("Verón", 33, "Mediocampista"),
    new Jugador("Braña", 30, "Mediocampista"),
    new Jugador("Enzo Pérez", 24, "Mediocampista"),
    new Jugador("Gata Fernández", 27, "Delantero"),
    new Jugador("Mauro Boselli", 25, "Delantero"),
    new Jugador("Leandro Benítez", 28, "Mediocampista"),
  ],
  Huracán: [
    new Jugador("Barovero", 28, "Arquero"),
    new Jugador("Domínguez", 29, "Defensor"),
    new Jugador("Goltz", 27, "Defensor"),
    new Jugador("Quintana", 26, "Defensor"),
    new Jugador("Araujo", 25, "Defensor"),
    new Jugador("Montenegro", 32, "Mediocampista"),
    new Jugador("Toranzo", 29, "Mediocampista"),
    new Jugador("Patricio Toranzo", 28, "Mediocampista"),
    new Jugador("Wanchope Ábila", 27, "Delantero"),
    new Jugador("Norberto Briasco", 25, "Delantero"),
    new Jugador("Lucas Barrios", 30, "Delantero"),
  ],
};
